# Generated by Django 5.2 on 2026-05-13 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_connectionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.CharField(default='по запросу', max_length=100, verbose_name='Цена')),
                ('currency', models.CharField(default='KGS', max_length=10, verbose_name='Валюта')),
                ('period', models.CharField(default='месяц', max_length=50, verbose_name='Период оплаты')),
                ('max_objects', models.CharField(default='1', max_length=50, verbose_name='Лимит объектов')),
                ('max_devices', models.CharField(default='5', max_length=50, verbose_name='Лимит устройств')),
                ('max_users', models.CharField(default='2', max_length=50, verbose_name='Лимит пользователей')),
                ('history_days', models.CharField(default='30', max_length=50, verbose_name='Хранение истории (дней)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Популярный')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Отключен')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='cms.tariff', verbose_name='Тариф'),
        ),
    ]
