# Generated by Django 5.2 on 2026-05-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_tariff_organization_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='ID устройства')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('device_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип устройства')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Статус')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('relay_status', models.BooleanField(default=False, verbose_name='Реле включено')),
                ('allow_remote_control', models.BooleanField(default=False, verbose_name='Разрешено удалённое управление')),
                ('voltage', models.FloatField(blank=True, null=True, verbose_name='Напряжение (V)')),
                ('current', models.FloatField(blank=True, null=True, verbose_name='Ток (A)')),
                ('power', models.FloatField(blank=True, null=True, verbose_name='Мощность (W)')),
                ('energy', models.FloatField(blank=True, null=True, verbose_name='Энергия (kWh)')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последний контакт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='cms.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField(blank=True, null=True, verbose_name='Напряжение (V)')),
                ('current', models.FloatField(blank=True, null=True, verbose_name='Ток (A)')),
                ('power', models.FloatField(blank=True, null=True, verbose_name='Мощность (W)')),
                ('energy', models.FloatField(blank=True, null=True, verbose_name='Энергия (kWh)')),
                ('relay_status', models.BooleanField(default=False, verbose_name='Реле включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время измерения')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='cms.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Энергетический показание',
                'verbose_name_plural': 'Энергетические показатели',
                'ordering': ['-created_at'],
            },
        ),
    ]
