# Generated by Django 5.2 on 2026-05-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_device_energyreading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energyreading',
            options={'ordering': ['-created_at'], 'verbose_name': 'Показание устройства', 'verbose_name_plural': 'Показания устройств'},
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='device',
            name='max_power_limit',
            field=models.FloatField(default=2.5, verbose_name='Лимит мощности (kW)'),
        ),
        migrations.AddField(
            model_name='device',
            name='object_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='device',
            name='zone_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Зона / точка'),
        ),
        migrations.AlterField(
            model_name='device',
            name='allow_remote_control',
            field=models.BooleanField(default=True, verbose_name='Разрешено удалённое управление'),
        ),
        migrations.AlterField(
            model_name='device',
            name='current',
            field=models.FloatField(default=0, verbose_name='Ток (A)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('smart_socket', 'Умная розетка'), ('energy_meter', 'Счётчик энергии'), ('sensor', 'Датчик'), ('relay_controller', 'Контроллер реле')], default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='energy',
            field=models.FloatField(default=0, verbose_name='Энергия (kWh)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='power',
            field=models.FloatField(default=0, verbose_name='Мощность (W)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('free', 'Свободно'), ('assigned', 'Назначено'), ('active', 'Активно'), ('inactive', 'Неактивно'), ('blocked', 'Заблокировано'), ('maintenance', 'На обслуживании')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='device',
            name='voltage',
            field=models.FloatField(default=0, verbose_name='Напряжение (V)'),
        ),
        migrations.AlterField(
            model_name='energyreading',
            name='current',
            field=models.FloatField(default=0, verbose_name='Ток (A)'),
        ),
        migrations.AlterField(
            model_name='energyreading',
            name='energy',
            field=models.FloatField(default=0, verbose_name='Энергия (kWh)'),
        ),
        migrations.AlterField(
            model_name='energyreading',
            name='power',
            field=models.FloatField(default=0, verbose_name='Мощность (W)'),
        ),
        migrations.AlterField(
            model_name='energyreading',
            name='voltage',
            field=models.FloatField(default=0, verbose_name='Напряжение (V)'),
        ),
    ]
